# This is a config for E2B sandbox template.
# You can use template ID (t6q82p6znq4of4o7yuqy) or template name (vibe-2025) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-2025") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-2025") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-2025')

team_id = "76e7eb99-5424-464e-9317-87125271b30b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-2025"
template_id = "t6q82p6znq4of4o7yuqy"
